# Generated by Django 6.1 on 2026-09-19 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Customized', 'Customized'), ('work', 'Work'), ('study', 'Study'), ('design', 'Design'), ('projects', 'Projects'), ('personal', 'Personal')], max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('remind', models.BooleanField(default=True)),
                ('remind_time', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(default='#c084fc', max_length=7)),
                ('pin_fav', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
