# Generated by Django 6.1 on 2026-09-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='custom_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='custom_remind_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
