# Generated by Django 6.1 on 2026-09-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_acc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myacc',
        ),
    ]
