# Generated by Django 6.1 on 2026-09-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_acc', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
